version: 1
disable_existing_loggers: false

formatters:
    default:
        format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"

handlers:
    default:
        class: logging.StreamHandler
        formatter: default

root:
    level: INFO
    handlers: [default]

loggers:
    uvicorn:
        level: INFO
        handlers: [default]
        propagate: false

    uvicorn.error:
        level: INFO
        handlers: [default]
        propagate: false

    uvicorn.access:
        level: WARNING
        handlers: [default]
        propagate: false

    # Suppress HTTP request logs from httpx
    httpx:
        level: ERROR
        handlers: [default]
        propagate: false

    # Suppress MCP client logs
    mcp:
        level: ERROR
        handlers: [default]
        propagate: false

    mcp.client:
        level: ERROR
        handlers: [default]
        propagate: false

    mcp.client.streamable_http:
        level: ERROR
        handlers: [default]
        propagate: false