# ============================================================================
# Build Stages Configuration
# ============================================================================
# This file defines the build pipeline for the combined Docker image that
# packages both the FastAPI backend and Flutter frontend into a single
# container with Nginx + Supervisord.

# Content-hash image tag — deterministic from file hashes so immutable ECR repos
# get a new tag only when source actually changes.
locals {
  # force_rebuild is folded into the tag so that a forced rebuild produces a
  # distinct tag, avoiding ImageTagAlreadyExistsException on immutable repos.
  combined_image_tag = substr(md5(join("", [
    filemd5("${path.module}/../Dockerfile.combined"),
    filemd5("${path.module}/../nginx-combined.conf"),
    filemd5("${path.module}/../supervisord.conf"),
    filemd5("${path.module}/../../requirements.txt"),
    md5(join("", [
      for f in fileset("${path.module}/../../bondable", "**/*.py") :
      filemd5("${path.module}/../../bondable/${f}")
    ])),
    filemd5("${path.module}/../../flutterui/pubspec.lock"),
    filemd5("${path.module}/../../flutterui/web/index.html"),
    md5(join("", [
      for f in fileset("${path.module}/../../flutterui/lib", "**/*.dart") :
      filemd5("${path.module}/../../flutterui/lib/${f}")
    ])),
    var.maintenance_mode ? "maintenance" : "normal",
    var.maintenance_message,
    var.theme_config_path,
    var.force_rebuild,
  ])), 0, 12)
}

# Build combined Docker image (Flutter frontend + FastAPI backend)
resource "null_resource" "build_combined_image" {
  depends_on = [
    aws_ecr_repository.backend,
    aws_ecr_repository_policy.backend
  ]

  triggers = {
    # Rebuild when content hash changes (covers code, deps, Dockerfiles, configs, force_rebuild)
    image_tag = local.combined_image_tag
  }

  lifecycle {
    create_before_destroy = false
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -e  # Exit on error

      # Verify Docker is running
      if ! docker info > /dev/null 2>&1; then
        echo "Error: Docker daemon is not running"
        exit 1
      fi

      # Login to ECR (use base registry URL, not repo-specific URL)
      ECR_REGISTRY="${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
      echo "Authenticating with ECR at $ECR_REGISTRY..."

      # Clear ALL existing credentials to prevent Keychain conflicts on macOS
      # (docker logout + security delete ensures no stale Keychain entries)
      docker logout $ECR_REGISTRY 2>/dev/null || true
      if [[ "$OSTYPE" == "darwin"* ]]; then
        while security delete-internet-password -s "$ECR_REGISTRY" 2>/dev/null; do :; done
      fi

      aws ecr get-login-password --region ${var.aws_region} | \
        docker login --username AWS --password-stdin $ECR_REGISTRY

      # Check if maintenance mode is enabled
      if [ "${var.maintenance_mode}" = "true" ]; then
        echo "========================================="
        echo "MAINTENANCE MODE ENABLED"
        echo "Building lightweight maintenance page..."
        echo "========================================="

        # Derive paths from theme config
        THEME_CONFIG="flutterui/${var.theme_config_path}"
        THEME_CSS="$${THEME_CONFIG%.json}.css"

        # Verify theme config exists
        if [ ! -f "$THEME_CONFIG" ]; then
          echo "Error: Theme config not found at $THEME_CONFIG"
          exit 1
        fi

        # Verify CSS file exists (should be generated by theme generator)
        if [ ! -f "$THEME_CSS" ]; then
          echo "Error: Theme CSS not found at $THEME_CSS"
          echo "Run: cd flutterui && dart run tool/generate_theme.dart -c ${var.theme_config_path}"
          exit 1
        fi

        # Extract values from JSON using jq
        THEME_NAME=$(jq -r '.themeName' "$THEME_CONFIG")
        LOGO_PATH=$(jq -r '.logoPath' "$THEME_CONFIG")

        echo "Theme: $THEME_NAME"
        echo "Logo: $LOGO_PATH"
        echo "Message: ${var.maintenance_message}"

        # Prepare build context
        TEMP_DIR=$(mktemp -d)
        echo "Using temporary build directory: $TEMP_DIR"

        cp deployment/maintenance/index.html "$TEMP_DIR/"
        cp "$THEME_CSS" "$TEMP_DIR/maintenance_theme.css"
        cp deployment/Dockerfile.maintenance "$TEMP_DIR/Dockerfile"

        # Copy logo if it exists
        if [ -f "flutterui/assets/$LOGO_PATH" ]; then
          cp "flutterui/assets/$LOGO_PATH" "$TEMP_DIR/logo.png"
        else
          # Create a placeholder 1x1 transparent PNG if logo doesn't exist
          echo "Warning: Logo not found at flutterui/assets/$LOGO_PATH, using placeholder"
          printf '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > "$TEMP_DIR/logo.png"
        fi

        # Build and push maintenance image
        cd "$TEMP_DIR"
        docker buildx build --platform linux/amd64 \
          --build-arg "MAINTENANCE_MESSAGE=${var.maintenance_message}" \
          --build-arg "THEME_NAME=$THEME_NAME" \
          -t ${aws_ecr_repository.backend.repository_url}:${local.combined_image_tag} \
          --push .

        cd - > /dev/null
        rm -rf "$TEMP_DIR"

        # Verify image was pushed
        aws ecr describe-images \
          --repository-name ${aws_ecr_repository.backend.name} \
          --region ${var.aws_region} \
          --image-ids imageTag=${local.combined_image_tag} > /dev/null 2>&1

        if [ $? -eq 0 ]; then
          echo "========================================="
          echo "✓ Maintenance page deployed successfully!"
          echo "  Theme: $THEME_NAME"
          echo "  Message: ${var.maintenance_message}"
          echo "========================================="
        else
          echo "Error: Failed to verify maintenance image in ECR"
          exit 1
        fi

      else
        # Normal combined build
        echo "========================================="
        echo "Building combined Docker image..."
        echo "  (Flutter frontend + FastAPI backend)"
        echo "========================================="

        # Check if Flutter is installed
        if ! command -v flutter &> /dev/null; then
          echo "Error: Flutter is not installed or not in PATH"
          echo "Please install Flutter: https://flutter.dev/docs/get-started/install"
          exit 1
        fi

        # Build Flutter web app locally (outside Docker)
        cd flutterui

        echo "Enabling Flutter web support..."
        flutter config --enable-web --no-analytics

        echo "Getting Flutter dependencies..."
        flutter pub get

        echo "Building Flutter web app with API_BASE_URL=/rest"
        flutter build web --release \
          --no-tree-shake-icons \
          --dart-define=API_BASE_URL=/rest \
          --dart-define=ENABLE_AGENTS=true

        if [ ! -d "build/web" ]; then
          echo "Error: Flutter build failed - build/web directory not found"
          exit 1
        fi

        echo "✓ Flutter web app built successfully"

        # Go back to project root
        cd ..

        echo "========================================="
        echo "Building and pushing combined Docker image..."
        echo "========================================="

        # Verify Dockerfile exists
        if [ ! -f "deployment/Dockerfile.combined" ]; then
          echo "Error: deployment/Dockerfile.combined not found"
          exit 1
        fi

        # Check if image already exists in ECR (immutable tags — skip push if so)
        if aws ecr describe-images \
          --repository-name ${aws_ecr_repository.backend.name} \
          --region ${var.aws_region} \
          --image-ids imageTag=${local.combined_image_tag} > /dev/null 2>&1; then
          echo "========================================="
          echo "✓ Image tag ${local.combined_image_tag} already exists in ECR — skipping build"
          echo "========================================="
        else
          # Build and push combined image
          docker buildx build --platform linux/amd64 \
            -t ${aws_ecr_repository.backend.repository_url}:${local.combined_image_tag} \
            -f deployment/Dockerfile.combined --push .
        fi

        # Verify image exists
        aws ecr describe-images \
          --repository-name ${aws_ecr_repository.backend.name} \
          --region ${var.aws_region} \
          --image-ids imageTag=${local.combined_image_tag} > /dev/null 2>&1

        if [ $? -eq 0 ]; then
          echo "========================================="
          echo "✓ Combined image verified in ECR!"
          echo "  - Tag: ${local.combined_image_tag}"
          echo "========================================="
        else
          echo "Error: Failed to verify combined image in ECR"
          exit 1
        fi
      fi
    EOT

    working_dir = "${path.module}/../.."
  }

  provisioner "local-exec" {
    when    = destroy
    command = "echo 'Combined Docker image will remain in ECR for potential reuse'"
  }
}
