"""initial_schema

Revision ID: 2731cf82e217
Revises:
Create Date: 2026-04-08 10:25:30.410892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2731cf82e217'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('auth_oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('sign_in_method', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='_folder_name_user_uc')
    )
    with op.batch_alter_table('agent_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_folders_user_id'), ['user_id'], unique=False)

    op.create_table('bedrock_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bedrock_messages', schema=None) as batch_op:
        batch_op.create_index('idx_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_thread_created', ['thread_id', 'created_at'], unique=False)
        batch_op.create_index('idx_thread_user_index', ['thread_id', 'user_id', 'message_index'], unique=False)

    op.create_table('connection_oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('connection_name', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('connection_oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_oauth_states_connection_name'), ['connection_name'], unique=False)

    op.create_table('files',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_path', 'file_hash', 'owner_user_id', name='_file_path_hash_user_uc')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('last_run_error', sa.String(), nullable=True),
    sa.Column('last_thread_id', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('user_agent_sort_orders',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'agent_id')
    )
    op.create_table('user_connection_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('connection_name', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connection_name', name='_user_connection_uc')
    )
    with op.batch_alter_table('user_connection_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_connection_tokens_connection_name'), ['connection_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_connection_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('agent_folder_assignments',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['agent_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'user_id')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('default_group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=True)

    op.create_table('group_users',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('session_state', sa.JSON(), nullable=True),
    sa.Column('last_agent_id', sa.String(), nullable=True),
    sa.Column('scheduled_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_job_id'], ['scheduled_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_scheduled_job_id'), ['scheduled_job_id'], unique=False)

    op.create_table('agent_groups',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'group_id')
    )
    op.create_table('bedrock_agent_options',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('bedrock_agent_id', sa.String(), nullable=False),
    sa.Column('bedrock_agent_alias_id', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('tool_resources', sa.JSON(), nullable=False),
    sa.Column('mcp_tools', sa.JSON(), nullable=False),
    sa.Column('mcp_resources', sa.JSON(), nullable=False),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.Column('file_storage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('bedrock_agent_options', schema=None) as batch_op:
        batch_op.create_index('idx_bedrock_agent_id', ['bedrock_agent_id'], unique=False)

    op.create_table('knowledge_base_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('ingestion_job_id', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'agent_id', name='_kb_file_agent_uc')
    )
    with op.batch_alter_table('knowledge_base_files', schema=None) as batch_op:
        batch_op.create_index('idx_kb_files_agent', ['agent_id'], unique=False)
        batch_op.create_index('idx_kb_files_status', ['ingestion_status'], unique=False)

    op.create_table('vector_stores',
    sa.Column('vector_store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('default_for_agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('knowledge_base_id', sa.String(), nullable=True),
    sa.Column('embedding_model_arn', sa.String(), nullable=True),
    sa.Column('storage_configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['default_for_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('vector_store_id'),
    sa.UniqueConstraint('knowledge_base_id'),
    sa.UniqueConstraint('name', 'owner_user_id', name='_vector_store_name_user_uc')
    )
    op.create_table('bedrock_vector_store_files',
    sa.Column('vector_store_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vector_stores.vector_store_id'], ),
    sa.PrimaryKeyConstraint('vector_store_id', 'file_id')
    )
    with op.batch_alter_table('bedrock_vector_store_files', schema=None) as batch_op:
        batch_op.create_index('idx_vector_store_file', ['vector_store_id', 'file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bedrock_vector_store_files', schema=None) as batch_op:
        batch_op.drop_index('idx_vector_store_file')

    op.drop_table('bedrock_vector_store_files')
    op.drop_table('vector_stores')
    with op.batch_alter_table('knowledge_base_files', schema=None) as batch_op:
        batch_op.drop_index('idx_kb_files_status')
        batch_op.drop_index('idx_kb_files_agent')

    op.drop_table('knowledge_base_files')
    with op.batch_alter_table('bedrock_agent_options', schema=None) as batch_op:
        batch_op.drop_index('idx_bedrock_agent_id')

    op.drop_table('bedrock_agent_options')
    op.drop_table('agent_groups')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_scheduled_job_id'))

    op.drop_table('threads')
    op.drop_table('group_users')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_slug'))

    op.drop_table('agents')
    op.drop_table('agent_folder_assignments')
    with op.batch_alter_table('user_connection_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_connection_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_connection_tokens_connection_name'))

    op.drop_table('user_connection_tokens')
    op.drop_table('user_agent_sort_orders')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_next_run_at'))

    op.drop_table('scheduled_jobs')
    op.drop_table('groups')
    op.drop_table('files')
    with op.batch_alter_table('connection_oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_oauth_states_connection_name'))

    op.drop_table('connection_oauth_states')
    with op.batch_alter_table('bedrock_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_thread_user_index')
        batch_op.drop_index('idx_thread_created')
        batch_op.drop_index('idx_session_id')

    op.drop_table('bedrock_messages')
    with op.batch_alter_table('agent_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_folders_user_id'))

    op.drop_table('agent_folders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('auth_oauth_states')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
